version: "3.9"

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "4000:4200"
    env_file: .env
    networks:
      - backend

  database:
    container_name: database
    image: database
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
      ports:
      - "8080:80"
    networks:
      - frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - backend

volumes:
  postgres_data:


networks:
  backend:
  frontend:
